# Generated by Django 2.2.4 on 2021-04-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20210413_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='message_likes',
            field=models.ManyToManyField(blank=True, related_name='message_likes', to='user_login_app.User'),
        ),
    ]
